_target_: src.tasks.lightning_module.DDSPDecoderTrainTask

preprocessor:
  _target_: src.data.preprocessor.F0LoudnessRMSPreprocessor

decoder:
  _target_: src.models.tcn_decoder.TCNdecoder
  in_channels: 16                                                                 
  hidden_channels: 32                                                             
  out_channels: 32                                                                
  n_blocks: 4 
  kernel_size: 3
  stride: 1
  dilation_base: 2
  apply_padding: True
  deploy_residual: True
  input_keys: ['f0_scaled','loudness_scaled']
  input_sizes: [1,1]
  output_keys: ['amplitude','harmonic_distribution','noise_bands']
  output_sizes: [1,100,65]

synth: 
  _target_: src.synths.hpn_synth.HpNSynth
  sample_rate: 16000
  block_size: 64
  reverb_scale: 10

criterion: 
  _target_: src.loss_functions.loss_functions.rec_loss
  scales: [2048, 1024, 512, 256, 128, 64]
  overlap: 0.75

optimizer:
  _target_: torch.optim.AdamW
  _partial_: True
  lr: 0.001

scheduler:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  _partial_: True
  gamma: 0.98
  verbose: True

scheduler_steps: 10000