# @package _global_

defaults:
  - _self_
  - data: flute_16000_250.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: gru/large_gru_decoder
  #- model: distillation/gru2gru_L2S.yaml
  #- model: ddx7/tcnres_f0ld_fmstr
  #- model: distillation/hpn2ddx7/tcn2ddx7_fmstr
  - callbacks: no_logger_callbacks.yaml
  - logger: null
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "eval"

tags: ["250 fr","16000 sr","s4","flute2trumpet"]

# teacher checkpoint path for KD evaluation
#model:
# path: "${oc.env:LARGE_GRU_FLUTE_16000_250}"

# passing checkpoint path is necessary for evaluation
ckpt_path: "${oc.env:SMALL_GRU_FLUTE_16000_250}"
#ckpt_path: "${oc.env:SMALL_GRU2GRU_FLUTE_16000_250}"
#ckpt_path: "${oc.env:TCN2DDX7_VIOLIN_16000_250}"
#ckpt_path: "${oc.env:DDX7_VIOLIN_16000_250}"

# seed for random number generators in pytorch, numpy and python.random
seed: 391219

#logger:
#  wandb:
#    name: "large_gru_flute_16000_250_${now:%Y-%m-%d}_${now:%H-%M-%S}"
#    tags: ${tags}
#    group: "decoders"
#  aim:
#    experiment: "audio_generation"

#data:
#  batch_size: 1
