_target_: src.tasks.lightning_module.DDSPDecoderTrainTask

preprocessor:
  _target_: src.data.preprocessor.F0LoudnessRMSPreprocessor

decoder:
  _target_: src.models.s4_decoder.S4decoder
  d_model: 256 # REMEMBER: S4 d_model = d_model*n_input_features
  d_state: 64
  dropout: 0.2 
  n_blocks: 5
  prenorm: False
  diag: False
  lr: 0.001
  measure: legs
  mode: nplr
  input_keys: ['f0_scaled','loudness_scaled']
  input_sizes: [1,1]
  output_keys: ['amplitude','harmonic_distribution','noise_bands']
  output_sizes: [1,100,65]

synth: 
  _target_: src.synths.hpn_synth.HpNSynth
  sample_rate: 16000
  block_size: 64

criterion: 
  _target_: src.loss_functions.loss_functions.rec_loss
  scales: [2048, 1024, 512, 256, 128, 64]
  overlap: 0.75

optimizer:
  _target_: torch.optim.AdamW
  _partial_: True
  lr: 0.001

scheduler:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  _partial_: True
  gamma: 0.98
  verbose: True

scheduler_steps: 10000